echo Building WAR ...
call mvn -f C:\Users\kozia\eclipse\workspace\mpb\spring\pom.xml -e clean package
echo Building VUE ...
call yarn --cwd C:\Users\kozia\eclipse\workspace\mpb\vue -e clean build
echo Deploying WAR ...
call pscp -scp -pw 99Pomidor! C:\Users\kozia\eclipse\workspace\mpb\spring\target\mpb-api.war koziarskim@mpb.noovitec.com:/opt/tomcat/webapps/
echo Deploying VUE ...
call pscp -r -scp -pw 99Pomidor! C:\Users\kozia\eclipse\workspace\mpb\vue\dist koziarskim@mpb.noovitec.com:/home/koziarskim/git/mpb/vue/
